version: 2.1
jobs:
  build:
    docker:https://raw.githubusercontent.com/zacky46/kernel-script/main/dtb.sh
      - image: okta10/docker:ubuntu
    steps:
      - run:
          name: Building Kernel
          command: |
            wget https://raw.githubusercontent.com/denialinden/kernel-script/main/sync.sh
            bash sync.sh stable clang
            cd kernel
            wget https://raw.githubusercontent.com/denialinden/kernel-script/main/dtb.sh
            bash dtb.sh lavender clang qpnp
            git apply qti.patch
            bash dtb.sh lavender clang qti
            git restore .
            wget https://raw.githubusercontent.com/denialinden/kernel-script/main/run.sh
            bash run.sh lavender newcam clang
            bash run.sh lavender oldcam clang
            wget https://raw.githubusercontent.com/denialinden/kernel-script/main/final.sh
            bash final.sh clang
            
